### ISSUE TITLE
unable to find JAVA_HOME

### ISSUE THREAD

**Issue by eravi-roshan** [mzagar/jenkins-slave-jdk-maven-git#1]
even after ensuring sylinks /opt/jdk/latest and /usr/local/apache-maven exist and point to respective folders. i am getting below error when in pull it as jenkins slave to be build .

[Project_package] $ /usr/local/apache-maven/bin/mvn package
Error: JAVA_HOME is not defined correctly.
  We cannot execute /opt/jdk1.8.0_161//bin/java
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

**Comment by eravi-roshan** [comment]
i tried to set the node properties as well for JAVA_HOME. but still the same error.

Commit message: "Merge pull request #198 from GeraldScott/master"
 > git rev-list --no-walk c24bb1ae41bfd5980ce9f0aa8b9a636b920c71fd # timeout=10
[Project_package] $ /usr/local/apache-maven/bin/mvn package
Error: JAVA_HOME is not defined correctly.
  We cannot execute /opt/jdk1.8.0_161/bin/java
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

**Comment by eravi-roshan** [comment]
further i see that jdk included in dockerfile is moved out from the location. hence the jenkins build of the image is not working.

[root@puppetnode ~]# wget --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz
--2018-04-25 02:30:28--  http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 72.247.229.40
Connecting to download.oracle.com (download.oracle.com)|72.247.229.40|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz [following]
--2018-04-25 02:30:28--  https://edelivery.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.15.242.48, 2600:140f:3000:184::2d3e, 2600:140f:3000:1a2::2d3e
Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.15.242.48|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz?AuthParam=1524623549_08f054a9b141ca4e5802e5b149e0b682 [following]
--2018-04-25 02:30:29--  http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz?AuthParam=1524623549_08f054a9b141ca4e5802e5b149e0b682
Connecting to download.oracle.com (download.oracle.com)|72.247.229.40|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-04-25 02:30:32 ERROR 404: Not Found.

**Comment by mzagar** [comment]
fixed with https://github.com/mzagar/jenkins-slave-jdk-maven-git/commit/88dd94200bc363aedf969456ca4dcb7e15f103e2

now using jdk 1.8.0_172, mvn 3.5.3, git 1.9.1
